type ExtType =
  | "#EXTM3U"
  | "#EXTINF"
  | "#EXT-X-VERSION"
  | "#EXT-X-TARGETDURATION"
  | "#EXT-X-MEDIA-SEQUENCE"
  | "#EXT-X-PLAYLIST-TYPE"
  | "#EXT-X-ALLOW-CACHE"
  | "#EXT-X-STREAM-INF"
  | "#EXT-X-MEDIA"
  | "#EXT-X-KEY"
  | "#EXT-X-BYTERANGE"
  | "#EXT-X-DISCONTINUITY"
  | "#EXT-X-DISCONTINUITY-SEQUENCE"
  | "#EXT-X-PROGRAM-DATE-TIME"
  | "#EXT-X-INDEPENDENT-SEGMENTS"
  | "#EXT-X-ENDLIST"
  | "#EXT-X-MAP"
  | "#EXT-X-START"
  | "#EXT-X-RENDITION-REPORT"
  | "#EXT-X-MEDIA-SEQUENCE-DISCONTINUITY"
  | "#EXT-X-DATERANGE"
  | "#EXT-X-TARGETDURATION-REACHED"
  | "#EXT-X-SERVER-CONTROL"
  | "#EXT-X-VERSIONING"
  | "#EXT-X-I-FRAMES-ONLY"
  | "#EXT-X-INDEPENDENT-SEGMENTS-DISCONTINUITY"
  | "#EXT-X-SESSION-DATA"
  | "#EXT-X-SESSION-KEY"
  | "#EXT-X-PRELOAD-HINT"
  | "#EXT-X-RENDITION-GROUP-ID"
  | "#EXT-X-RENDITION-LANGUAGE"
  | "#EXT-X-RENDITION-ASSOCIATED-PROPERTY"
  | "#EXT-X-RENDITION-URI"
  | "#EXT-X-CUE-OUT"
  | "#EXT-X-CUE-IN"
  | "#EXT-X-RENDITION-GROUP"
  | "#EXT-X-RENDITION-TO-PROGRAM"
  | "#EXT-X-PROGRAM-DATE-TIME-OFFSET"
  | "#EXT-X-CONTENT-IDENTIFIER"
  | "#EXT-X-DATERANGE-ID"
  | "#EXT-X-SERVER-CONTROL-COMMAND"
  | "#EXT-X-SERVER-CONTROL-HOLD-BACK"
  | "#EXT-X-SERVER-CONTROL-PART-HOLD-BACK"
  | "#EXT-X-SERVER-CONTROL-MAX-DURATION"
  | "#EXT-X-SERVER-CONTROL-MAX-AGE"
  | "#EXT-X-SERVER-CONTROL-CAN-SKIP-UNTIL"
  | "#EXT-X-SERVER-CONTROL-CAN-SKIP-DATERANGES"
  | "#EXT-X-START-DURATION"
  | "#EXT-X-CUE-OUT-CONT-DURATION"
  | "#EXT-X-PROGRAM-DATE-TIME-SERVER"
  | "#EXT-X-CONTENT-KEY"
  | "#EXT-X-DISCONTINUITY-ITEM"
  | "#EXT-X-SCTE35"
  | "#EXT-X-CUE-OUT-PTS"
  | "#EXT-X-CUE-IN-PTS"
  | "#EXT-X-CUE-START-PTS"
  | "#EXT-X-CUE-END-PTS"
  | "#EXT-X-CUE-OUT-CONT-PTS"
  | "#EXT-X-MEDIA-RENDITION-REPORT"
  | "#EXT-X-RELATIVE-CUE-OUT"
  | "#EXT-X-RELATIVE-CUE-IN"
  | "#EXT-X-RELATIVE-CUE-OUT-CONT"
  | "#EXT-X-CUE-OUT-DURATION"
  | "#EXT-X-MAP-BYTERANGE"
  | "#EXT-X-CUE-OUT-CONT-ID"
  | "#EXT-X-CUE-IN-DURATION"
  | "#EXT-X-CUE-START-DURATION"
  | "#EXT-X-CUE-END-DURATION"
  | "#EXT-X-CUE-OUT-CONT-DURATION-MS";

const extTypeList = [
  "#EXTM3U",
  "#EXTINF",
  "#EXT-X-VERSION",
  "#EXT-X-TARGETDURATION",
  "#EXT-X-MEDIA-SEQUENCE",
  "#EXT-X-PLAYLIST-TYPE",
  "#EXT-X-ALLOW-CACHE",
  "#EXT-X-STREAM-INF",
  "#EXT-X-MEDIA",
  "#EXT-X-KEY",
  "#EXT-X-BYTERANGE",
  "#EXT-X-DISCONTINUITY",
  "#EXT-X-DISCONTINUITY-SEQUENCE",
  "#EXT-X-PROGRAM-DATE-TIME",
  "#EXT-X-INDEPENDENT-SEGMENTS",
  "#EXT-X-ENDLIST",
  "#EXT-X-MAP",
  "#EXT-X-START",
  "#EXT-X-RENDITION-REPORT",
  "#EXT-X-MEDIA-SEQUENCE-DISCONTINUITY",
  "#EXT-X-DATERANGE",
  "#EXT-X-TARGETDURATION-REACHED",
  "#EXT-X-SERVER-CONTROL",
  "#EXT-X-VERSIONING",
  "#EXT-X-I-FRAMES-ONLY",
  "#EXT-X-INDEPENDENT-SEGMENTS-DISCONTINUITY",
  "#EXT-X-SESSION-DATA",
  "#EXT-X-SESSION-KEY",
  "#EXT-X-PRELOAD-HINT",
  "#EXT-X-RENDITION-GROUP-ID",
  "#EXT-X-RENDITION-LANGUAGE",
  "#EXT-X-RENDITION-ASSOCIATED-PROPERTY",
  "#EXT-X-RENDITION-URI",
  "#EXT-X-CUE-OUT",
  "#EXT-X-CUE-IN",
  "#EXT-X-RENDITION-GROUP",
  "#EXT-X-RENDITION-TO-PROGRAM",
  "#EXT-X-PROGRAM-DATE-TIME-OFFSET",
  "#EXT-X-CONTENT-IDENTIFIER",
  "#EXT-X-DATERANGE-ID",
  "#EXT-X-SERVER-CONTROL-COMMAND",
  "#EXT-X-SERVER-CONTROL-HOLD-BACK",
  "#EXT-X-SERVER-CONTROL-PART-HOLD-BACK",
  "#EXT-X-SERVER-CONTROL-MAX-DURATION",
  "#EXT-X-SERVER-CONTROL-MAX-AGE",
  "#EXT-X-SERVER-CONTROL-CAN-SKIP-UNTIL",
  "#EXT-X-SERVER-CONTROL-CAN-SKIP-DATERANGES",
  "#EXT-X-START-DURATION",
  "#EXT-X-CUE-OUT-CONT-DURATION",
  "#EXT-X-PROGRAM-DATE-TIME-SERVER",
  "#EXT-X-CONTENT-KEY",
  "#EXT-X-DISCONTINUITY-ITEM",
  "#EXT-X-SCTE35",
  "#EXT-X-CUE-OUT-PTS",
  "#EXT-X-CUE-IN-PTS",
  "#EXT-X-CUE-START-PTS",
  "#EXT-X-CUE-END-PTS",
  "#EXT-X-CUE-OUT-CONT-PTS",
  "#EXT-X-MEDIA-RENDITION-REPORT",
  "#EXT-X-RELATIVE-CUE-OUT",
  "#EXT-X-RELATIVE-CUE-IN",
  "#EXT-X-RELATIVE-CUE-OUT-CONT",
  "#EXT-X-CUE-OUT-DURATION",
  "#EXT-X-MAP-BYTERANGE",
  "#EXT-X-CUE-OUT-CONT-ID",
  "#EXT-X-CUE-IN-DURATION",
  "#EXT-X-CUE-START-DURATION",
  "#EXT-X-CUE-END-DURATION",
  "#EXT-X-CUE-OUT-CONT-DURATION-MS",
];

// TODO: append more tags
type ExtAttribute = "tvg-logo" | "group-title" | "tvg-name" | "TVG-ID";

export { ExtType, extTypeList, ExtAttribute };
